---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by filipe.
--- DateTime: 05/03/2021 17:35

scroll = {
    pos = 500,
    from = 100,
    to = -250,
    speed = 50
}
pos_title = { pos = -200, too=200,speed = 20}


function update_intro(self, dt)
    if scroll.pos > scroll.to then
        scroll.pos = scroll.pos - dt * scroll.speed
    end
    --if scroll.pos < scroll.to then
    plane_back.coords[1] = plane_back.coords[1] + plane_back.speed * dt
    if plane_back.coords[1]>plane_back.to[1] then
        plane_back.coords[1] = plane_back.to[1]
    end

    plane_back.coords[2] = plane_back.coords[2] + plane_back.speed * dt
    if plane_back.coords[2]>plane_back.to[2] then
        plane_back.coords[2] = plane_back.to[2]
    end
    plane_back.coords[3] = plane_back.coords[3] - plane_back.speed_scale * dt
    if plane_back.coords[3]<0 then
        plane_back.coords[3] = 0
    end
    plane_back.rot = lerp(plane_back.rot, plane_back.rotTarget, plane_back.rotSpeed*dt)
    plane_back.rotTarget = math.random(-2,2)
    pos_title.pos = pos_title.pos + pos_title.speed * dt
    if pos_title.pos > pos_title.too then pos_title.pos = pos_title.too end
end
function lerp(a, b, k) --smooth transitions
    if a == b then
        return a
    else
        if math.abs(a-b) < 0.005 then return b else return a * (1-k) + b * k end
    end
end


