---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Filipe Mendes Silva.
--- DateTime: 12/02/2021 15:00
---

-- Cette ligne permet d'afficher des traces dans la console pendant l'éxécution
io.stdout:setvbuf('no')

-- empeche le filtre alias en cas de scale

--love.graphics.setDefaultFilter("nearest")

json = require("libs/json")

-- Cette ligne permet de déboguer pas à pas dans ZeroBraneStudio
if arg[#arg] == "debug" then require("mobdebug").start() end

print("Launching escape from 1997")
print("loading config")
require("config/config")
print("config Loaded")
local screen_width, screen_height = conf['display']['width'], conf['display']['height']
love.window.setMode(screen_width, screen_height, {fullscreen=false, fullscreentype='desktop', msaa=16})

function dprint(texte)
    if conf['debug']['active']=="true" then
        print(texte)
    end
end
dprint("loading languages")
require("languages/languages")
dprint('default language is ' .. lang)
dprint("loading Audio")
require("audio/audio")
dprint("Audio Loaded")
MAudio.musics.intro:setVolume(MAudio.music_general_volume)
MAudio.musics.intro:play()
dprint("loading fonts")
require("fonts/fonts")
dprint("fonts Loaded")

dprint("loading keyboard")
require("keyboard/keyboard")
dprint("keyboard Loaded")
dprint("loading gamepad")
require("gamepad/gamepad")
dprint("gamepad Loaded")
dprint("loading game")
require("game/game")
dprint("game Loaded")


-- init first time

