---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by filipe.
--- DateTime: 05/03/2021 17:35
---
---
coords = {
    x = 0,
    y = 0,
    z = 0
}
square = {
    sommets = 8,
    {x = -1.0, y = -1.0, z = -1.0},{x = -1.0, y = 1.0, z = -1.0},{x = 1.0, y = 1.0, z = -1.0},{x = 1.0, y = -1.0, z = -1.0},
    {x = -1.0, y = -1.0, z = 1.0},{x = -1.0, y = 1.0, z = 1.0},{x = 1.0, y = 1.0, z = 1.0},{x = 1.0, y = -1.0, z = 1.0},
}

for i=1,square.sommets do
    dprint(square[i])
end



function draw_screen_game()
    love.graphics.print("GAME running")
    love.graphics.print("\nGAME Type is "..Game.type)
end
