---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by filipe.
--- DateTime: 05/03/2021 17:35
---

--screen_intro2 = love.graphics.newImage("assets/intro.png")

function draw_screen_intro2()
    love.graphics.print("INTRO PART 2")
--    love.graphics.draw(screen_intro2,300,300)
end
