---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by filipe.
--- DateTime: 05/03/2021 17:35
---
--logo_studio_image = love.graphics.newImage("assets/logo_studio.png")
logo_studio_image = love.graphics.newImage("assets/logo_256x256.png")
logo_joystick = love.graphics.newImage("assets/white-joystick.png")


function draw_screen_logo_studio()
    love.graphics.setColor( 1, 1, 1, 1 )
    love.graphics.draw(
            logo_studio_image,
            (love.graphics.getWidth() - logo_studio_image:getWidth())/2,
            (love.graphics.getHeight() - logo_studio_image:getHeight())/2
    )
    love.graphics.draw(
            logo_joystick,
            (love.graphics.getWidth() - logo_joystick:getWidth()*.1)/2,
            ((love.graphics.getHeight() - logo_studio_image:getHeight())/2) + logo_studio_image:getHeight() + .1 * logo_joystick:getHeight()/2,
            0,
            .1,
            .1

    )

    love.graphics.print('Press A button',
            (love.graphics.getWidth() - logo_joystick:getWidth()*.1)/2 - 20,
            ((love.graphics.getHeight() - logo_studio_image:getHeight())/2) + logo_studio_image:getHeight() + .1 * logo_joystick:getHeight()/2 + logo_joystick:getHeight() * .1
    )
    love.graphics.print('or Spacebar',
            (love.graphics.getWidth() - logo_joystick:getWidth()*.1)/2 - 20,
            (10+ (love.graphics.getHeight() - logo_studio_image:getHeight())/2) + logo_studio_image:getHeight() + .1 * logo_joystick:getHeight()/2 + logo_joystick:getHeight() * .1
    )

    --love.graphics.print("C'est une \npériode sombre!")
end
