---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by filipe.
--- DateTime: 05/03/2021 17:35
---
screen_intro = love.graphics.newImage("assets/manathan.png")
scale_intro = love.graphics.getWidth() / screen_intro:getWidth()
plane_image = love.graphics.newImage("assets/planeur_back.png")
sx = 1.5
plane_back = {
    coords = {-plane_image:getWidth() * sx, 0, sx},
    from = {-100, -100, 1},
    to = {love.graphics.getWidth()/2 , love.graphics.getHeight()/2, 0},
    speed_scale = .08,
    speed = 60,
    rot = 0,
    rotTarget = 0,
    rotSpeed = .1
}

function draw_screen_intro()
    --love.graphics.print("INTRO SCREEN")
    love.graphics.draw(screen_intro,0, scroll.pos,0,scale_intro)
    love.graphics.draw(
            logo_joystick,
            (love.graphics.getWidth() - logo_joystick:getWidth()*.1)/2,
            ((love.graphics.getHeight() - logo_studio_image:getHeight())/2) + logo_studio_image:getHeight() + .1 * logo_joystick:getHeight()/2,
            0,
            .1,
            .1

    )
    love.graphics.setFont(systemFont)
    love.graphics.print('Press A button',
            (love.graphics.getWidth() - logo_joystick:getWidth()*.1)/2 - 20,
            ((love.graphics.getHeight() - logo_studio_image:getHeight())/2) + logo_studio_image:getHeight() + .1 * logo_joystick:getHeight()/2 + logo_joystick:getHeight() * .1
    )
    love.graphics.print('or Spacebar',
            (love.graphics.getWidth() - logo_joystick:getWidth()*.1)/2 - 20,
            (10+ (love.graphics.getHeight() - logo_studio_image:getHeight())/2) + logo_studio_image:getHeight() + .1 * logo_joystick:getHeight()/2 + logo_joystick:getHeight() * .1
    )
    love.graphics.setFont(font_title)
    love.graphics.print('Escape from New-York 1997',100,pos_title.pos)
    love.graphics.setFont(systemFont)
    love.graphics.draw(plane_image,plane_back.coords[1], plane_back.coords[2],plane_back.rot,plane_back.coords[3])
end


